### ISSUE TITLE
FlywayException: Validate failed. Migration Checksum mismatch

### ISSUE THREAD

**Issue by mrbarbitoff** [epam/NGB#115]
NGB v. 2.5.1. fails to run on a remote host with an exception "validate failed. Migration Checksum
 mismatch". As far as I understand, this issue has something to do with the usage of the existing database that worked OK with the previous versions of NGB. The error is reproduced with both standalone jar provided at GitHub and self-compiled jar.
Am I doing something wrong?

Complete error log with traceback:

```
Nov 09, 2017 9:11:32 PM org.apache.catalina.core.StandardService startInternal
INFO: Starting service Tomcat
Nov 09, 2017 9:11:32 PM org.apache.catalina.core.StandardEngine startInternal
INFO: Starting Servlet Engine: Apache Tomcat/8.5.6
Nov 09, 2017 9:11:36 PM org.apache.catalina.core.ApplicationContext log
INFO: Initializing Spring embedded WebApplicationContext
Nov 09, 2017 9:11:49 PM org.apache.catalina.core.StandardService stopInternal
INFO: Stopping service Tomcat
ERROR [09/11/2017 21:11:49][SpringApplication] Application startup failed
org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'flyway' defined in class path resource [conf/catgenome/applicationContext-flyway.xml]: Invocation of init method failed; nested exception is org.flywaydb.core.api.FlywayException: Validate failed. Migration Checksum mismatch for migration 2016.11.21.17.58
-> Applied to database : 1897633945
-> Resolved locally    : 89084448
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.initializeBean(AbstractAutowireCapableBeanFactory.java:1589)
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:554)
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:483)
        at org.springframework.beans.factory.support.AbstractBeanFactory$1.getObject(AbstractBeanFactory.java:306)
        at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:230)
        at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:302)
        at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:197)
        at org.springframework.beans.factory.support.DefaultListableBeanFactory.preInstantiateSingletons(DefaultListableBeanFactory.java:759)
        at org.springframework.context.support.AbstractApplicationContext.finishBeanFactoryInitialization(AbstractApplicationContext.java:861)
        at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:541)
        at org.springframework.boot.context.embedded.EmbeddedWebApplicationContext.refresh(EmbeddedWebApplicationContext.java:122)
        at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:761)
        at org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:371)
        at org.springframework.boot.SpringApplication.run(SpringApplication.java:315)
        at org.springframework.boot.SpringApplication.run(SpringApplication.java:1186)
        at org.springframework.boot.SpringApplication.run(SpringApplication.java:1175)
        at com.epam.catgenome.app.Application.main(Application.java:40)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.springframework.boot.loader.MainMethodRunner.run(MainMethodRunner.java:48)
        at org.springframework.boot.loader.Launcher.launch(Launcher.java:87)
        at org.springframework.boot.loader.Launcher.launch(Launcher.java:50)
        at org.springframework.boot.loader.JarLauncher.main(JarLauncher.java:51)
Caused by: org.flywaydb.core.api.FlywayException: Validate failed. Migration Checksum mismatch for migration 2016.11.21.17.58
-> Applied to database : 1897633945
-> Resolved locally    : 89084448
        at org.flywaydb.core.Flyway.doValidate(Flyway.java:1108)
        at org.flywaydb.core.Flyway.access$300(Flyway.java:62)
        at org.flywaydb.core.Flyway$1.execute(Flyway.java:1012)
        at org.flywaydb.core.Flyway$1.execute(Flyway.java:1006)
        at org.flywaydb.core.Flyway.execute(Flyway.java:1418)
        at org.flywaydb.core.Flyway.migrate(Flyway.java:1006)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.invokeCustomInitMethod(AbstractAutowireCapableBeanFactory.java:1719)
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.invokeInitMethods(AbstractAutowireCapableBeanFactory.java:1656)
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.initializeBean(AbstractAutowireCapableBeanFactory.java:1585)
        ... 24 more
```

If no simple solution can be found, I can just make a clear NGB database and re-register all the files that are registered in the current one. However, I'm just wondering whether this issue can be handled in any other way.

Thanks in advance. :)

**Comment by mzueva** [comment]
@mrbarbitoff , unfortunately there is really an issue with migration to 2.5.1. We've prepared scripts to fix DB. This problem is described in this issue https://github.com/epam/NGB/issues/88.
The solution is the following:

The archive migration_fix_windows.zip (migration_fix_linux.zip) contains SQL script checksum.sql for fixing migration in DB and shell script fix_migration.sh to run it.
In order to launch SQL script, you can use H2 console, if you have one installed (make sure that NGB is not running while you are connecting to it's DB using console).
Otherwise follow this instruction:
[migration_fix_linux.zip](https://github.com/epam/NGB/files/1466440/migration_fix_linux.zip)
[migration_fix_windows.zip](https://github.com/epam/NGB/files/1466442/migration_fix_windows.zip)

1. Download and unpack **migration_fix.zip**
2. Download H2 driver [(h2.jar)](http://repo2.maven.org/maven2/com/h2database/h2/1.3.176/h2-1.3.176.jar)
3. Shut down NGB server and make a backup of **H2** folder from NGB installation folder
4. Change directory to the unpacked **migration_fix** folder and run **fix_migration.sh** with two input arguments: path to H2 driver and path to NGb installation folder, e.g.:
`fix_migration.sh /home/downloads/h2-1.3.176.jar /opt/NGB`

After applying the script 2.5.1 will start on top of previous 2.5 installation

**Comment by sidoruka** [comment]
Hope this helped, closing as outdated

**Comment by aurybocker** [comment]
I ran into the same problem in my local environment, I just configured the H2 maven plugin:
            <plugin>
                <groupId>org.flywaydb</groupId>
                <artifactId>flyway-maven-plugin</artifactId>
                <configuration>
                    <url>jdbc:h2:~/test</url>
                    <user>sa</user>
                    <password/>
                </configuration>
            </plugin>
and run the command  mvn flyway:clean, finally to check the status you can run status  mvn flyway:info.
That's the way I fixed the migration error.
