### ISSUE TITLE
[Target identification] Target isn't created from the "Homologs" panel

### ISSUE THREAD

**Issue by maryvictol** [epam/NGB#1165]
Target isn't created from the **Homologs** panel

**To Reproduce:**
1. Open the Homologs panel with the found list of homologous orthogroups (for ex. use `Fruitfly` dataset, coordinates  211000022279188: 1375 - 2253)
2. Click any orthogroup from the list to view the context menu
3. Select _Create target_ item from the context menu

**Actual results:**
- _Create target_ page opens with the empty genes table
- Console error:
```
TypeError: this.$timeout is not a function
    at ngbTargetsFormService.createTargetFromHomologs (app.bundle.42c2f5ffa41e7c61d3bc.js:98060:12)
    at dispatcher.emit (vendors.bundle.1ee7da16615383821004.js:140893:7)
    at dispatcher.emitSimpleEvent (app.bundle.42c2f5ffa41e7c61d3bc.js:57112:12)
    at ngbHomologsTableContextMenuController.createTarget (app.bundle.42c2f5ffa41e7c61d3bc.js:71246:23)
    at fn (eval at compile (vendors.bundle.1ee7da16615383821004.js:59730:15), <anonymous>:4:372)
    at expensiveCheckFn (vendors.bundle.1ee7da16615383821004.js:60817:18)
    at callback (vendors.bundle.1ee7da16615383821004.js:71196:17)
    at Scope.$eval (vendors.bundle.1ee7da16615383821004.js:62598:28)
    at Scope.$apply (vendors.bundle.1ee7da16615383821004.js:62698:25)
    at HTMLButtonElement.<anonymous> (vendors.bundle.1ee7da16615383821004.js:71201:23)
    at HTMLButtonElement.dispatch (vendors.bundle.1ee7da16615383821004.js:162705:27)
    at elemData.handle (vendors.bundle.1ee7da16615383821004.js:162509:28)
```

**Expected behavior**
 _Create target_ page opens with the genes table filled with all genes from the selected orthogroup.

**Comment by maryvictol** [comment]
Verified as fixed
