### ISSUE TITLE
"Genes" table isn't filtered by any column

### ISSUE THREAD

**Issue by maryvictol** [epam/NGB#1166]
**Genes** table isn't filtered by any column

**To Reproduce**
1. Open any Dataset
2. Open **Genes** tab
3. Try to filter by any column

**Actual results:**
- **Genes** table isn't filtered
- Console error:
```
TypeError: Cannot read properties of undefined (reading 'genes')
    at ngbTargetsFormService.targetGenesChanged (app.bundle.42c2f5ffa41e7c61d3bc.js:97183:46)
    at ngbTargetsFormService.needSaveGeneChanges (app.bundle.42c2f5ffa41e7c61d3bc.js:97275:82)
    at ngbTargetGenesFilterInputController.apply (app.bundle.42c2f5ffa41e7c61d3bc.js:100669:40)
    at ngbTargetGenesFilterInputController.onKeyPress (app.bundle.42c2f5ffa41e7c61d3bc.js:100659:16)
    at fn (eval at compile (vendors.bundle.1ee7da16615383821004.js:59730:15), <anonymous>:4:378)
    at expensiveCheckFn (vendors.bundle.1ee7da16615383821004.js:60817:18)
    at callback (vendors.bundle.1ee7da16615383821004.js:71196:17)
    at Scope.$eval (vendors.bundle.1ee7da16615383821004.js:62598:28)
    at Scope.$apply (vendors.bundle.1ee7da16615383821004.js:62698:25)
    at HTMLInputElement.<anonymous> (vendors.bundle.1ee7da16615383821004.js:71201:23)
    at HTMLInputElement.dispatch (vendors.bundle.1ee7da16615383821004.js:162705:27)
    at elemData.handle (vendors.bundle.1ee7da16615383821004.js:162509:28)
```

**Comment by maryvictol** [comment]
Verified as fixed
