### ISSUE TITLE
Error "2" registering VCF Files

### ISSUE THREAD

**Issue by Fappian** [epam/NGB#177]
i tried to register multiple files generated by CLC Workbenchwith the following command: 
`ngb reg_file my_genome BP701_1.sorted.vcf -n BP701_1 -t`
after some seconds i got an error message without any suitable error message:

> 09:27:56.859 [main] ERROR com.epam.ngb.cli.manager.command.handler.http.FileRegistrationHandler - 2
> 09:27:56.875 [main] ERROR com.epam.ngb.cli.manager.command.handler.http.FileRegistrationHandler - Failed to register files: /my/path/BP701_1.sorted.vcf.

is there any verbose option to get more informations about this error? 
I also verified my files with vcf-tools to be sure, that they are okay.

Any ideas? thanks in advance

**Comment by sidoruka** [comment]
Hello @Fappian , this is strange. Typically it *shall* provide more verbose output.
At a glance, looks like connectivity/compatibility problem. Could you please specify:
* Which NGB version are you using? Is it dockerized, prebuilt release or built from sources using a specific commit?
* Is server side running fine and GUI works as well? Is it located on the same machine as CLI?
* Is any additional configuration is made to CLI? (e.g. `ngb set_srv ..` or manual changes to the configuration file)

@mzueva , any ideas on such behaviour?

**Comment by Fappian** [comment]
Hi @sidoruka,
i'm using NGB via Docker in the latest version. I didn't made any additional configurations to CLI. The server and the GUI are working well. I tried to import the files again and became a dirrent error message:

>08:17:13.440 [main] ERROR com.epam.ngb.cli.manager.command.handler.http.FileRegistrationHandler - Your operation has been aborted due to CATGenome browser has encountered a server problem.
08:17:13.452 [main] ERROR com.epam.ngb.cli.manager.command.handler.http.FileRegistrationHandler - Failed to register files: /my/path/BP701_1.sorted.vcf.

now i found an error in `/opt/ngb/logs/catgenome-error.log`:

> ERROR [21/03/2018 08:17:13][http-nio-8080-exec-3][com.epam.catgenome.controller.
ExceptionHandlerAdvice] This operation has been aborted: uri=/catgenome/restapi/
vcf/register;client=127.0.0.1.
java.lang.ArrayIndexOutOfBoundsException

My VCF file has a length of  2,033,800 lines and every row has the same amount of values (tab seperated)

**Comment by mzueva** [comment]
Hello @Fappian !
You've corrrectly located the error log at `/opt/ngb/logs/catgenome-error.log`.
Is it possible to post here the full stack trace? It should look something like that:
```
ERROR [17/03/2018 11:03:33][http-nio-8080-exec-2][com.epam.catgenome.controller.ExceptionHandlerAdvice] This operation has been aborted: uri=/catgenome/files;client=0:0:0:0:0:0:0:1.
java.lang.IllegalArgumentException: Specified path does not exist: null
	at org.springframework.util.Assert.isTrue(Assert.java:68)
	at com.epam.catgenome.manager.FileManager.loadDirectoryContents(FileManager.java:1949)
	at com.epam.catgenome.controller.UtilsController.loadDirectoryContents(UtilsController.java:107)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at org.springframework.web.method.support.InvocableHandlerMethod.doInvoke(InvocableHandlerMethod.java:220)
	at org.springframework.web.method.support.InvocableHandlerMethod.invokeForRequest(InvocableHandlerMethod.java:134)
	at org.springframework.web.servlet.mvc.method.annotation.ServletInvocableHandlerMethod.invokeAndHandle(ServletInvocableHandlerMethod.java:116)
	at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.invokeHandlerMethod(RequestMappingHandlerAdapter.java:827)
	at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.handleInternal(RequestMappingHandlerAdapter.java:738)
	at org.springframework.web.servlet.mvc.method.AbstractHandlerMethodAdapter.handle(AbstractHandlerMethodAdapter.java:85)
	at org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:963)
...
```
It would greatly help us to determine the reason for such strange behavior. If you would like to keep stack trace private, you may send it to me by email.

**Comment by mzueva** [comment]
@Fappian If you are running NGB as a docker container, could you please check the logs output from the docker:
`docker logs ngb-container-id`
It is possible that full stack trace will be present there.

**Comment by Fappian** [comment]
it's still the same error message on `docker logs `
