### ISSUE TITLE
Lucene is missing from release 2.5.1.374.1

### ISSUE THREAD

**Issue by szilvajuhos** [epam/NGB#206]
Hullo, seems the latest release (catgenome-2.5.1.374.1.jar) is missing the Lucene jar:

```Caused by: java.lang.IllegalArgumentException: An SPI class of type org.apache.lucene.codecs.Codec with name 'Lucene62' does not exist.  You need to add the corresponding JAR file supporting this SPI to your classpath.  The current classpath supports the following names: [Lucene60]```

Cheers:
Szilva

**Comment by szilvajuhos** [comment]
Actually it is the `lucene-backward-codecs-6.6.0.jar` that is missing:
```
 $ unzip -l catgenome-2.5.1.374.1.jar| grep "lucene"
  2403623  2016-04-01 14:36   BOOT-INF/lib/lucene-core-6.0.0.jar
   402470  2016-04-01 14:37   BOOT-INF/lib/lucene-queryparser-6.0.0.jar
  1494915  2016-04-01 14:37   BOOT-INF/lib/lucene-analyzers-common-6.0.0.jar
   106563  2016-04-01 14:37   BOOT-INF/lib/lucene-grouping-6.0.0.jar
   177235  2016-04-01 14:37   BOOT-INF/lib/lucene-facet-6.0.0.jar
   221499  2016-04-01 14:37   BOOT-INF/lib/lucene-queries-6.0.0.jar
   137488  2016-04-01 14:37   BOOT-INF/lib/lucene-sandbox-6.0.0.jar
$ unzip -l catgenome-2.5.jar| grep "lucene"
  2783533  2017-05-30 07:29   BOOT-INF/lib/lucene-core-6.6.0.jar
   404764  2017-05-30 07:30   BOOT-INF/lib/lucene-queryparser-6.6.0.jar
  1513789  2017-05-30 07:30   BOOT-INF/lib/lucene-analyzers-common-6.6.0.jar
   107680  2017-05-30 07:30   BOOT-INF/lib/lucene-grouping-6.6.0.jar
   196324  2017-05-30 07:30   BOOT-INF/lib/lucene-facet-6.6.0.jar
    87409  2017-05-30 07:30   BOOT-INF/lib/lucene-backward-codecs-6.6.0.jar
   237890  2017-05-30 07:30   BOOT-INF/lib/lucene-queries-6.6.0.jar
   169064  2017-05-30 07:30   BOOT-INF/lib/lucene-sandbox-6.6.0.jar
```

**Comment by SilinPavel** [comment]
Hello @szilvajuhos, thank you for the issue.
Could you please provide more details here (full stack trace and what you trying to do).
Btw here is my output of our commands: 
```
unzip -l catgenome-2.5.jar| grep "lucene"
  2403623  2016-04-01 14:36   BOOT-INF/lib/lucene-core-6.0.0.jar
   402470  2016-04-01 14:37   BOOT-INF/lib/lucene-queryparser-6.0.0.jar
  1494915  2016-04-01 14:37   BOOT-INF/lib/lucene-analyzers-common-6.0.0.jar
   106563  2016-04-01 14:37   BOOT-INF/lib/lucene-grouping-6.0.0.jar
   177235  2016-04-01 14:37   BOOT-INF/lib/lucene-facet-6.0.0.jar
   221499  2016-04-01 14:37   BOOT-INF/lib/lucene-queries-6.0.0.jar
   137488  2016-04-01 14:37   BOOT-INF/lib/lucene-sandbox-6.0.0.jar

> unzip -l catgenome-2.5.1.374.1.jar| grep "lucene"
  2403623  2016-04-01 14:36   BOOT-INF/lib/lucene-core-6.0.0.jar
   402470  2016-04-01 14:37   BOOT-INF/lib/lucene-queryparser-6.0.0.jar
  1494915  2016-04-01 14:37   BOOT-INF/lib/lucene-analyzers-common-6.0.0.jar
   106563  2016-04-01 14:37   BOOT-INF/lib/lucene-grouping-6.0.0.jar
   177235  2016-04-01 14:37   BOOT-INF/lib/lucene-facet-6.0.0.jar
   221499  2016-04-01 14:37   BOOT-INF/lib/lucene-queries-6.0.0.jar
   137488  2016-04-01 14:37   BOOT-INF/lib/lucene-sandbox-6.0.0.jar
```
It seems that here is a problem with lucene version

We will take this in our backlog, thanks again!

**Comment by szilvajuhos** [comment]
Hi, you are right, it is actually a daily build jar that I have used, not v2.5, my bad . This jar size is 98780642 (4ef2fc7ccb3e418584967b2814452200) I have downloaded as "catgenome-30_July.jar", sorry with no proper version name. 
Nevertheless, the error I am getting with 2.5.1.374.1.jar is:
```
ERROR [31/10/2018 18:28:08][http-nio-8080-exec-8][com.epam.catgenome.controller.ExceptionHandlerAdvice] This operation has been aborted: uri=/catgenome/filter/group;client=x.x.x.x.
java.lang.IllegalArgumentException: Could not load codec 'Lucene62'.  Did you forget to add lucene-backward-codecs.jar?
        at org.apache.lucene.index.SegmentInfos.readCodec(SegmentInfos.java:429)
        at org.apache.lucene.index.SegmentInfos.readCommit(SegmentInfos.java:349)
        at org.apache.lucene.index.SegmentInfos.readCommit(SegmentInfos.java:284)
[...]
Caused by: java.lang.IllegalArgumentException: An SPI class of type org.apache.lucene.codecs.Codec with name 'Lucene62' does not exist.  You need to add the corresponding JAR file supporting this SPI to your classpath.  The current classpath supports the following names: [Lucene60]
        at org.apache.lucene.util.NamedSPILoader.lookup(NamedSPILoader.java:116)
        at org.apache.lucene.codecs.Codec.forName(Codec.java:116)
        at org.apache.lucene.index.SegmentInfos.readCodec(SegmentInfos.java:417)
```
With the latest dev version (catgenome-2.6.0.835.1.jar) I can get lucene-backward-codecs back and no exception.
