### ISSUE TITLE
Error is displaying, if non-admin user is trying to view datasets permissions using CLI.

### ISSUE THREAD

**Issue by vpolyakov88** [epam/NGB#247]
#218 

1. Login in NGB CLI as user (user shall have read permissions at least one dataset).
2. Try to view list of datasets with permissions by command `ngb ld -perm -t`

exp.: list of datasets without permissions is displayed.
act.: error is displayed.
```
ngb ld -perm -t
 ID PARENT_ID         NAME        CREATED_DATE ITEMS_COUNT    LAST_OPENED_DATE
 20           test_dataset 21-12-2018 00:00:00           0 25-12-2018 00:00:00
18:03:43.575 [main] ERROR com.epam.ngb.cli.manager.command.handler.http.PrintPermissionsHelper - An error occurred during building permissions
com.epam.ngb.cli.exception.ApplicationException: Failed to find permissions for PROJECT with ID 20
        at com.epam.ngb.cli.manager.command.handler.http.AbstractHTTPCommandHandler.loadPermissions(AbstractHTTPCommandHandler.java:610) ~[ngb-cli-2.6.0.jar:?]
        at com.epam.ngb.cli.manager.command.handler.http.PrintPermissionsHelper.print(PrintPermissionsHelper.java:66) ~[ngb-cli-2.6.0.jar:?]
        at com.epam.ngb.cli.manager.command.handler.http.DatasetListHandler.lambda$printWithPermissions$0(DatasetListHandler.java:152) ~[ngb-cli-2.6.0.jar:?]
        at java.util.ArrayList.forEach(ArrayList.java:1257) [?:1.8.0_192-ea]
        at com.epam.ngb.cli.manager.command.handler.http.DatasetListHandler.printWithPermissions(DatasetListHandler.java:147) [ngb-cli-2.6.0.jar:?]
        at com.epam.ngb.cli.manager.command.handler.http.DatasetListHandler.runCommand(DatasetListHandler.java:122) [ngb-cli-2.6.0.jar:?]
        at com.epam.ngb.cli.manager.command.CommandManager.run(CommandManager.java:91) [ngb-cli-2.6.0.jar:?]
        at com.epam.ngb.cli.app.Application.createAndLaunchCommandManager(Application.java:258) [ngb-cli-2.6.0.jar:?]
        at com.epam.ngb.cli.app.Application.run(Application.java:220) [ngb-cli-2.6.0.jar:?]
        at com.epam.ngb.cli.app.Application.main(Application.java:206) [ngb-cli-2.6.0.jar:?]
```

**Comment by ekazachkova** [comment]
@vpolyakov88 , done
