### ISSUE TITLE
Unexpected error if admin search files using NGB CLI with flags "-l" and "-perm".

### ISSUE THREAD

**Issue by vpolyakov88** [epam/NGB#248]
#218 

Prerequisites: several files with similar names shall be registered (eg. fruitfly set).
1. Login in NGB CLI as admin.
2. Try to search files from prerequisites by CLI command `ngb s -l CantonS -t -perm`

exp.: list of files with info about permissions are displayed.
act.: list of files with info about permissions and error are displayed.

```
21:20:48.962 [main] ERROR com.epam.ngb.cli.manager.command.handler.http.PrintPermissionsHelper - An error occurred during building permissions
com.fasterxml.jackson.databind.JsonMappingException: No content to map due to end-of-input
 at [Source: ; line: 1, column: 0]
        at com.fasterxml.jackson.databind.JsonMappingException.from(JsonMappingException.java:255) ~[jackson-databind-2.7.5.jar:2.7.5]
        at com.fasterxml.jackson.databind.ObjectMapper._initForReading(ObjectMapper.java:3851) ~[jackson-databind-2.7.5.jar:2.7.5]
        at com.fasterxml.jackson.databind.ObjectMapper._readMapAndClose(ObjectMapper.java:3792) ~[jackson-databind-2.7.5.jar:2.7.5]
        at com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:2835) ~[jackson-databind-2.7.5.jar:2.7.5]
        at com.epam.ngb.cli.manager.command.handler.http.AbstractHTTPCommandHandler.loadPermissions(AbstractHTTPCommandHandler.java:606) ~[ngb-cli-2.6.0.jar:?]
        at com.epam.ngb.cli.manager.command.handler.http.PrintPermissionsHelper.print(PrintPermissionsHelper.java:66) ~[ngb-cli-2.6.0.jar:?]
        at com.epam.ngb.cli.manager.command.handler.http.SearchHandler.lambda$printWithPermissions$0(SearchHandler.java:95) ~[ngb-cli-2.6.0.jar:?]
        at java.util.ArrayList.forEach(ArrayList.java:1257) [?:1.8.0_192-ea]
        at com.epam.ngb.cli.manager.command.handler.http.SearchHandler.printWithPermissions(SearchHandler.java:90) [ngb-cli-2.6.0.jar:?]
        at com.epam.ngb.cli.manager.command.handler.http.SearchHandler.runCommand(SearchHandler.java:81) [ngb-cli-2.6.0.jar:?]
        at com.epam.ngb.cli.manager.command.CommandManager.run(CommandManager.java:91) [ngb-cli-2.6.0.jar:?]
        at com.epam.ngb.cli.app.Application.createAndLaunchCommandManager(Application.java:258) [ngb-cli-2.6.0.jar:?]
        at com.epam.ngb.cli.app.Application.run(Application.java:220) [ngb-cli-2.6.0.jar:?]
        at com.epam.ngb.cli.app.Application.main(Application.java:206) [ngb-cli-2.6.0.jar:?]
```

**Comment by ekazachkova** [comment]
@vpolyakov88 , done

**Comment by vpolyakov88** [comment]
tested
