### ISSUE TITLE
Error is displayed if non-admin user try to search file and use flag "-perm".

### ISSUE THREAD

**Issue by vpolyakov88** [epam/NGB#249]
#218 
Prerequisites: user shall have read permission at least on one file.
1. Login in NGB CLI as non-admin user.
2. Search file file by NGB CLI command `ngb s {file_name} -t -perm`

exp.: handled error is displayed.
act.: unhandled exception is displayed.
```
21:27:03.793 [main] ERROR com.epam.ngb.cli.manager.command.handler.http.PrintPermissionsHelper - An error occurred during building permissions
com.epam.ngb.cli.exception.ApplicationException: Failed to find permissions for BED with ID 3
        at com.epam.ngb.cli.manager.command.handler.http.AbstractHTTPCommandHandler.loadPermissions(AbstractHTTPCommandHandler.java:610) ~[ngb-cli-2.6.0.jar:?]
        at com.epam.ngb.cli.manager.command.handler.http.PrintPermissionsHelper.print(PrintPermissionsHelper.java:66) ~[ngb-cli-2.6.0.jar:?]
        at com.epam.ngb.cli.manager.command.handler.http.SearchHandler.lambda$printWithPermissions$0(SearchHandler.java:95) ~[ngb-cli-2.6.0.jar:?]
        at java.util.ArrayList.forEach(ArrayList.java:1257) [?:1.8.0_192-ea]
        at com.epam.ngb.cli.manager.command.handler.http.SearchHandler.printWithPermissions(SearchHandler.java:90) [ngb-cli-2.6.0.jar:?]
        at com.epam.ngb.cli.manager.command.handler.http.SearchHandler.runCommand(SearchHandler.java:81) [ngb-cli-2.6.0.jar:?]
        at com.epam.ngb.cli.manager.command.CommandManager.run(CommandManager.java:91) [ngb-cli-2.6.0.jar:?]
        at com.epam.ngb.cli.app.Application.createAndLaunchCommandManager(Application.java:258) [ngb-cli-2.6.0.jar:?]
        at com.epam.ngb.cli.app.Application.run(Application.java:220) [ngb-cli-2.6.0.jar:?]
        at com.epam.ngb.cli.app.Application.main(Application.java:206) [ngb-cli-2.6.0.jar:?]
```

**Comment by ekazachkova** [comment]
@vpolyakov88 , done
