### ISSUE TITLE
Issue when building Frontend for prod

### ISSUE THREAD

**Issue by mike-miroliubov** [epam/NGB#313]
Hi, 
I've tried building the NGB application from source and bumped into an issue with frontend part:
```
# npm run build

> NGB@2.6.0 build /opt/ngb/client
> npm run build:prod


> NGB@2.6.0 build:prod /opt/ngb/client
> webpack --env prod --prodBuild

[ Error: app.bundle.js from UglifyJs
  SyntaxError: Unexpected token: punc ({) [./~/keyboardjs/index.js:1,0]
      at /opt/ngb/client/node_modules/webpack/lib/optimize/UglifyJsPlugin.js:128:32
      at Array.forEach (native)
      at Compilation.<anonymous> (/opt/ngb/client/node_modules/webpack/lib/optimize/UglifyJsPlugin.js:44:10)
      at Compilation.applyPluginsAsync (/opt/ngb/client/node_modules/tapable/lib/Tapable.js:71:13)
      at Compilation.<anonymous> (/opt/ngb/client/node_modules/webpack/lib/Compilation.js:567:9)
      at Compilation.next (/opt/ngb/client/node_modules/tapable/lib/Tapable.js:67:11)
      at ExtractTextPlugin.<anonymous> (/opt/ngb/client/node_modules/extract-text-webpack-plugin/index.js:303:4)
      at Compilation.applyPluginsAsync (/opt/ngb/client/node_modules/tapable/lib/Tapable.js:71:13)
      at Compilation.<anonymous> (/opt/ngb/client/node_modules/webpack/lib/Compilation.js:563:8)
      at Compilation.next (/opt/ngb/client/node_modules/tapable/lib/Tapable.js:67:11)
      at ExtractTextPlugin.<anonymous> (/opt/ngb/client/node_modules/extract-text-webpack-plugin/index.js:279:5)
      at /opt/ngb/client/node_modules/async/lib/async.js:52:16
      at done (/opt/ngb/client/node_modules/async/lib/async.js:246:17)
      at /opt/ngb/client/node_modules/async/lib/async.js:44:16
      at /opt/ngb/client/node_modules/extract-text-webpack-plugin/index.js:270:6
      at /opt/ngb/client/node_modules/async/lib/async.js:52:16
      at done (/opt/ngb/client/node_modules/async/lib/async.js:246:17)
      at /opt/ngb/client/node_modules/async/lib/async.js:44:16
      at /opt/ngb/client/node_modules/extract-text-webpack-plugin/index.js:260:9
      at /opt/ngb/client/node_modules/webpack/lib/Compilation.js:469:4
      at Array.forEach (native)
      at callback (/opt/ngb/client/node_modules/webpack/lib/Compilation.js:468:14)
      at Compilation.<anonymous> (/opt/ngb/client/node_modules/webpack/lib/Compilation.js:489:4)
      at /opt/ngb/client/node_modules/webpack/lib/Compilation.js:332:10
      at /opt/ngb/client/node_modules/async/lib/async.js:52:16
      at Object.async.forEachOf.async.eachOf (/opt/ngb/client/node_modules/async/lib/async.js:236:30)
      at Object.async.forEach.async.each (/opt/ngb/client/node_modules/async/lib/async.js:209:22)
      at Compilation.addModuleDependencies (/opt/ngb/client/node_modules/webpack/lib/Compilation.js:185:8)
      at Compilation.processModuleDependencies (/opt/ngb/client/node_modules/webpack/lib/Compilation.js:170:7)
      at Compilation.<anonymous> (/opt/ngb/client/node_modules/webpack/lib/Compilation.js:476:8) ]

npm ERR! Linux 4.19.76-linuxkit
npm ERR! argv "/opt/node-v6.17.1-linux-x64/bin/node" "/opt/node-v6.17.1-linux-x64/bin/npm" "run" "build:prod"
npm ERR! node v6.17.1
npm ERR! npm  v3.10.10
npm ERR! code ELIFECYCLE
npm ERR! NGB@2.6.0 build:prod: `webpack --env prod --prodBuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the NGB@2.6.0 build:prod script 'webpack --env prod --prodBuild'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the NGB package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     webpack --env prod --prodBuild
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs NGB
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls NGB
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /opt/ngb/client/npm-debug.log

npm ERR! Linux 4.19.76-linuxkit
npm ERR! argv "/opt/node-v6.17.1-linux-x64/bin/node" "/opt/node-v6.17.1-linux-x64/bin/npm" "run" "build"
npm ERR! node v6.17.1
npm ERR! npm  v3.10.10
npm ERR! code ELIFECYCLE
npm ERR! NGB@2.6.0 build: `npm run build:prod`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the NGB@2.6.0 build script 'npm run build:prod'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the NGB package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     npm run build:prod
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs NGB
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls NGB
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /opt/ngb/client/npm-debug.log
```

This happens only for prod build, if I try to build dev configuration (`npm run build:dev`), it passes OK.

This also blocks  building the whole app using gradle...
As suggested in docs, I'm using NodeJS v6.9.5 via a simple Docker image:
```
# A development image to build NGB application
FROM ubuntu:16.04

#Install OpenJDK 8
RUN apt-get -y update && \
    apt-get -y install wget curl openjdk-8-jre

RUN cd opt && wget https://nodejs.org/dist/v6.9.5/node-v6.9.5-linux-x64.tar.gz && \
    tar xvf node-v6.9.5-linux-x64.tar.gz

ENV PATH="/opt/node-v6.9.5-linux-x64/bin:${PATH}"
``` 

Would be happy for any help. @sidoruka @rodichenko

**Comment by rodichenko** [comment]
@k-i-t-e sorry for the late reply - #317 should fix that error. Could you check this please?

**Comment by mike-miroliubov** [comment]
@rodichenko, looks good now, thank you! Let's close this ticket.
