### ISSUE TITLE
"gradlew buildDocker" fails with 5 test in gradle container

### ISSUE THREAD

**Issue by tomaszjacek** [epam/NGB#350]
Hi,

after command "./gradlew buildDocker"
my ubuntu system shows me an error

>FAILURE: Build failed with an exception.
>* What went wrong:
>Could not determine java version from '14.0.2'.

because it seems to be an missionimpossible to fix it I decided to use gradle docker image to build NGB docker image
here is list of commands

>cd /data/work/
>git clone https://github.com/epam/NGB.git
>cd NGB
>sudo docker pull gradle
>sudo docker run -u gradle -v "/data/work/NGB":/NGB -w /NGB gradle ./gradlew buildDocker

it goes smoothly and painlessly until the bad end... whole process fails with notification

>329 tests completed, 5 failed, 20 skipped
>:ngb:server:catgenome:test FAILED
>:buildJar FAILED
>FAILURE: Build failed with an exception.
>* What went wrong:
>Execution failed for task ':ngb:server:catgenome:test'.
> There were failing tests. See the report at: file:///NGB/server/catgenome/build/reports/tests/test/index.html
>* Try:
>Run with --stacktrace option to get the stack trace. Run with --info
>or --debug option to get more log output.
>BUILD FAILED

There are some information on index.html

>329 tests completed, 5 failed, 20 skipped
>VcfManagerTest. testGetNextFeature
>VcfManagerTest. testLoadSmallScaleVcfFile
>VcfManagerTest. testLoadStructuralVariations
>VcfManagerTest. testRegisterFile
>VcfManagerTest. testSaveLoadVcfFile

Do you know how to fix it?

Thank you,
tj

**Comment by jamesdalg** [comment]
I am also having this issue:
```
(base) jd@acadia:~/wgstools/NGB$ ./gradlew buildDocker --info --stacktrace
Initialized native services in: /home/jd/.gradle/native

FAILURE: Build failed with an exception.

* What went wrong:
Could not determine java version from '17.0.6'.

* Try:
Run with --debug option to get more log output.

* Exception is:
java.lang.IllegalArgumentException: Could not determine java version from '17.0.6'.
        at org.gradle.api.JavaVersion.toVersion(JavaVersion.java:70)
        at org.gradle.api.JavaVersion.current(JavaVersion.java:80)
        at org.gradle.internal.jvm.UnsupportedJavaRuntimeException.assertUsingVersion(UnsupportedJavaRuntimeException.java:29)
        at org.gradle.launcher.cli.JavaRuntimeValidationAction.execute(JavaRuntimeValidationAction.java:32)
        at org.gradle.launcher.cli.JavaRuntimeValidationAction.execute(JavaRuntimeValidationAction.java:24)
        at org.gradle.launcher.cli.ExceptionReportingAction.execute(ExceptionReportingAction.java:33)
        at org.gradle.launcher.cli.ExceptionReportingAction.execute(ExceptionReportingAction.java:22)
        at org.gradle.launcher.cli.CommandLineActionFactory$WithLogging.execute(CommandLineActionFactory.java:210)
        at org.gradle.launcher.cli.CommandLineActionFactory$WithLogging.execute(CommandLineActionFactory.java:174)
        at org.gradle.launcher.Main.doAction(Main.java:33)
        at org.gradle.launcher.bootstrap.EntryPoint.run(EntryPoint.java:45)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:568)
        at org.gradle.launcher.bootstrap.ProcessBootstrap.runNoExit(ProcessBootstrap.java:60)
        at org.gradle.launcher.bootstrap.ProcessBootstrap.run(ProcessBootstrap.java:37)
        at org.gradle.launcher.GradleMain.main(GradleMain.java:23)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:568)
        at org.gradle.wrapper.BootstrapMainStarter.start(BootstrapMainStarter.java:31)
        at org.gradle.wrapper.WrapperExecutor.execute(WrapperExecutor.java:108)
        at org.gradle.wrapper.GradleWrapperMain.main(GradleWrapperMain.java:61)
```
