### ISSUE TITLE
BUG: An error is displayed in console when opening the "SV_Sample1" dataset

### ISSUE THREAD

**Issue by Tatyana2022** [epam/NGB#599]
**Preconditions:**
Open Dev Console (F12)

**To Reproduce**

1. Go to 'NGB'
2. Go to **DATASETS** panel
3. Select **SV_Sample1** dataset
4. Look at console

**Expected behavior**
No errors in the console

**Actual behavior**
An error is displayed in the console: 

`Unhandled rejection TypeError: Cannot read properties of undefined (reading 'trustAsResourceUrl')    at http://oss-1204092014.us-east-1.elb.amazonaws.com:8080/catgenome/app.bundle.js:1106:27403    at tryCatcher (http://oss-1204092014.us-east-1.elb.amazonaws.com:8080/catgenome/app.bundle.js:326:16403)    at Promise._settlePromiseFromHandler (http://oss-1204092014.us-east-1.elb.amazonaws.com:8080/catgenome/app.bundle.js:326:9768)    at Promise._settlePromise (http://oss-1204092014.us-east-1.elb.amazonaws.com:8080/catgenome/app.bundle.js:326:11061)    at Promise._settlePromise0 (http://oss-1204092014.us-east-1.elb.amazonaws.com:8080/catgenome/app.bundle.js:326:12103)    at Promise._settlePromises (http://oss-1204092014.us-east-1.elb.amazonaws.com:8080/catgenome/app.bundle.js:326:13814)    at _drainQueueStep (http://oss-1204092014.us-east-1.elb.amazonaws.com:8080/catgenome/app.bundle.js:326:25315)    at _drainQueue (http://oss-1204092014.us-east-1.elb.amazonaws.com:8080/catgenome/app.bundle.js:326:25211)    at Async._drainQueues (http://oss-1204092014.us-east-1.elb.amazonaws.com:8080/catgenome/app.bundle.js:326:27224)    at Async.drainQueues (http://oss-1204092014.us-east-1.elb.amazonaws.com:8080/catgenome/app.bundle.js:326:24833)`

**Environment:**
 -  NGB Version: 2.6.1.2881
 - Browser: Chrome (93.0.4577.82)

**Comment by Tatyana2022** [comment]
***Verified***
