### ISSUE TITLE
BUG: Lineage tree visualization not showing in LINEAGE panel

### ISSUE THREAD

**Issue by Tatyana2022** [epam/NGB#758]
**BUG**
Lineage tree visualization not showing in LINEAGE panel

**Prerequisites:**
Open Console (F12)

**To Reproduce**
1. Go to NGB
2. Go to DATASETS panel
3. Select any dataset (e.g. **SV_Sample1**)
4. Go to VIEWS ->LINEAGE panel
5. Look at LINEAGE panel

**Expected result:**
1. The first one in the list related to the current dataset is displayed by default (e.g. Delete-test). Tree visualization is displayed in LINEAGE panel
2. No errors in the console

**Actual result:**
1. **No lineage tree visualization in the panel**. Only Lineage names are displayed in the 'Source' field
<img src="https://user-images.githubusercontent.com/83421565/152969260-7858bafd-7922-4e4b-a4d9-02ca0c4755b4.png" width="200" />
2. Errors are displayed in the console

```
app.bundle.941e0f9cbfe1aa419064.js:60 TypeError: Cannot convert undefined or null to object
    at Function.keys (<anonymous>)
    at Style.appendFromJson (app.bundle.941e0f9cbfe1aa419064.js:1049:33504)
    at Style.styfn$8.append (app.bundle.941e0f9cbfe1aa419064.js:1049:67335)
    at app.bundle.941e0f9cbfe1aa419064.js:1049:78708
    at app.bundle.941e0f9cbfe1aa419064.js:1049:78575
    at new Core (app.bundle.941e0f9cbfe1aa419064.js:1049:78589)
    at cytoscape (app.bundle.941e0f9cbfe1aa419064.js:1049:306849)
    at app.bundle.941e0f9cbfe1aa419064.js:1064:186330
    at app.bundle.941e0f9cbfe1aa419064.js:60:209795
    at completeOutstandingRequest (app.bundle.941e0f9cbfe1aa419064.js:60:51868)
    at app.bundle.941e0f9cbfe1aa419064.js:60:54712
```

**Environment:**
NGB version: 2.6.1.3308
Browser: Chrome Version 97.0.4692.99

**Comment by Tatyana2022** [comment]
Fixed and checked
